### ISSUE TITLE
链接过长破坏页面结构

### ISSUE THREAD

**Issue by xihale** [zigcc/zigcc.github.io#48]
![Screenshot_20250125_133343.jpg](https://github.com/user-attachments/assets/c9aa2d24-f5e3-4794-8c08-d36a5f9d2558)

建议在 global css 中添加
```css
a{
  line-break: anywhere;
}
```
